apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backstage
    app.kubernetes.io/instance: backstage-app
    app.kubernetes.io/name: backstage
  name: backstage
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/component: backstage
      app.kubernetes.io/instance: backstage
      app.kubernetes.io/name: backstage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backstage
        app.kubernetes.io/instance: backstage
        app.kubernetes.io/name: backstage
    spec:
      containers:
        - command:
            - node
            - packages/backend
          env:
            - name: APP_CONFIG_backend_listen_port
              value: '7007'
          envFrom:
            - secretRef:
                name: backstage-secrets
          image: gitea.yanello.net/marcus/backstage:latest@sha256:fe56fd20637824e3ed80db733b993beec8c3dd911b138d243bbfc4fc136dce73
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /.backstage/health/v1/liveness
              port: 7007
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: backstage-backend
          ports:
            - containerPort: 7007
              name: backend
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /.backstage/health/v1/readiness
              port: 7007
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 3
            httpGet:
              path: /.backstage/health/v1/liveness
              port: 7007
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
      imagePullSecrets:
        - name: gitea-pull-secrets
      restartPolicy: Always
      serviceAccount: backstage
      serviceAccountName: backstage

